### Aliases
alias ipy="python3 -m IPython"
alias info="info --vi-keys"
alias ls="ls -hF --color=auto"
alias l="ls -alrt"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
